language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy3"
os: linux
arch:
  - amd64
  - ppc64le
dist: focal
install:
  - pip install mock
  - pip install --upgrade .
script:
  - python src/tests/portpicker_test.py
  - python -c 'import sys; sys.exit(sys.version_info.major<=2)' && PYTHONPATH=src python src/tests/portserver_test.py
