language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
os: linux
arch:
  - amd64
  - ppc64le
dist: focal
install:
  - pip install mock
  - pip install --upgrade .
script:
  - python src/tests/portpicker_test.py
  - PYTHONPATH=src python src/tests/portserver_test.py
